// <auto-generated />
using System;
using GestaoTarefas.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestaoTarefas.Migrations
{
    [DbContext(typeof(GestaoTarefasDbContext))]
    [Migration("20231214173701_AddedTaskRequestAndChangedTasks")]
    partial class AddedTaskRequestAndChangedTasks
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GestaoTarefas.Domain.TaskRequests.TaskRequest", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("DeliveryRoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PickupRoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RequestStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaskDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("TaskRequests");

                    b.HasDiscriminator<string>("Type");
                });

            modelBuilder.Entity("GestaoTarefas.Domain.Tasks.Task", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("DeliveryRoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PickupRoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaskDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Tasks");

                    b.HasDiscriminator<string>("Type");
                });

            modelBuilder.Entity("GestaoTarefas.Domain.TaskRequests.DeliveryTaskRequest", b =>
                {
                    b.HasBaseType("GestaoTarefas.Domain.TaskRequests.TaskRequest");

                    b.Property<string>("ConfirmationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverContact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderContact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderName")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Delivery");
                });

            modelBuilder.Entity("GestaoTarefas.Domain.TaskRequests.SurveillanceTaskRequest", b =>
                {
                    b.HasBaseType("GestaoTarefas.Domain.TaskRequests.TaskRequest");

                    b.Property<string>("EmergencyNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FloorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasDiscriminator().HasValue("Surveillance");
                });

            modelBuilder.Entity("GestaoTarefas.Domain.Tasks.DeliveryTask", b =>
                {
                    b.HasBaseType("GestaoTarefas.Domain.Tasks.Task");

                    b.Property<string>("ConfirmationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverContact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderContact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderName")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Delivery");
                });

            modelBuilder.Entity("GestaoTarefas.Domain.Tasks.SurveillanceTask", b =>
                {
                    b.HasBaseType("GestaoTarefas.Domain.Tasks.Task");

                    b.Property<string>("EmergencyNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FloorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasDiscriminator().HasValue("Surveillance");
                });
#pragma warning restore 612, 618
        }
    }
}
