@startuml


actor GestorFrota
participant RobDroneGo <<system>>




GestorFrota-> RobDroneGo : adiciona novo tipo de robo
activate RobDroneGo


GestorFrota<-- RobDroneGo  : tipo de robo adicionado
deactivate RobDroneGo


@enduml
