@startuml


actor GestorFrota
participant GestaoDeInformacao <<component>>



GestorFrota-> GestaoDeInformacao : adiciona novo tipo de robo
activate GestaoDeInformacao


GestorFrota<-- GestaoDeInformacao  :  tipo de  robo adicionado
deactivate GestaoDeInformacao


@enduml
