// <auto-generated />
using System;
using GestaoTarefas.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestaoTarefas.Migrations
{
    [DbContext(typeof(GestaoTarefasDbContext))]
    [Migration("20231229032643_InitialDatabaseCreation")]
    partial class InitialDatabaseCreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GestaoTarefas.Domain.TaskRequests.TaskRequest", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("DeliveryRoomId")
                        .HasColumnType("char(36)");

                    b.Property<string>("IdentificationCode")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("varchar(255)")
                        .HasComputedColumnSql("CONCAT(Type,'-',RIGHT(CONCAT('000000000',Id),9))");

                    b.Property<Guid>("PickupRoomId")
                        .HasColumnType("char(36)");

                    b.Property<string>("RequestStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TaskDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("IdentificationCode")
                        .IsUnique();

                    b.ToTable("TaskRequests");

                    b.HasDiscriminator<string>("Type");
                });

            modelBuilder.Entity("GestaoTarefas.Domain.Tasks.Task", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("DeliveryRoomId")
                        .HasColumnType("char(36)");

                    b.Property<string>("IdentificationCode")
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("PickupRoomId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("RobotId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TaskDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("IdentificationCode")
                        .IsUnique();

                    b.ToTable("Tasks");

                    b.HasDiscriminator<string>("Type");
                });

            modelBuilder.Entity("GestaoTarefas.Domain.TaskRequests.DeliveryTaskRequest", b =>
                {
                    b.HasBaseType("GestaoTarefas.Domain.TaskRequests.TaskRequest");

                    b.Property<string>("ConfirmationCode")
                        .HasColumnType("longtext");

                    b.Property<string>("ReceiverContact")
                        .HasColumnType("longtext");

                    b.Property<string>("ReceiverName")
                        .HasColumnType("longtext");

                    b.Property<string>("SenderContact")
                        .HasColumnType("longtext");

                    b.Property<string>("SenderName")
                        .HasColumnType("longtext");

                    b.HasDiscriminator().HasValue("Delivery");
                });

            modelBuilder.Entity("GestaoTarefas.Domain.TaskRequests.SurveillanceTaskRequest", b =>
                {
                    b.HasBaseType("GestaoTarefas.Domain.TaskRequests.TaskRequest");

                    b.Property<string>("EmergencyNumber")
                        .HasColumnType("longtext");

                    b.Property<Guid>("FloorId")
                        .HasColumnType("char(36)");

                    b.HasDiscriminator().HasValue("Surveillance");
                });

            modelBuilder.Entity("GestaoTarefas.Domain.Tasks.DeliveryTask", b =>
                {
                    b.HasBaseType("GestaoTarefas.Domain.Tasks.Task");

                    b.Property<string>("ConfirmationCode")
                        .HasColumnType("longtext");

                    b.Property<string>("ReceiverContact")
                        .HasColumnType("longtext");

                    b.Property<string>("ReceiverName")
                        .HasColumnType("longtext");

                    b.Property<string>("SenderContact")
                        .HasColumnType("longtext");

                    b.Property<string>("SenderName")
                        .HasColumnType("longtext");

                    b.HasDiscriminator().HasValue("Delivery");
                });

            modelBuilder.Entity("GestaoTarefas.Domain.Tasks.SurveillanceTask", b =>
                {
                    b.HasBaseType("GestaoTarefas.Domain.Tasks.Task");

                    b.Property<string>("EmergencyNumber")
                        .HasColumnType("longtext");

                    b.Property<Guid>("FloorId")
                        .HasColumnType("char(36)");

                    b.HasDiscriminator().HasValue("Surveillance");
                });
#pragma warning restore 612, 618
        }
    }
}
