image: node:16


pipelines:
  default:
    - parallel:
        - step:
            name: Build and Test
            caches:
              - node
            script:
              - npm install
              - npm test
        - step:
            name: Code linting
            script:
              - npm install eslint
              - npx eslint .
            caches:
              - node
        - step:
            name: Deploy to VM
            deployment: production
            script:
            - echo "Deploying to VM"
            - cat deployPlaneamento.sh | ssh pipelineuser@vsgate-ssh.dei.isep.ipp.pt:11141
            - echo "Deployment step finished