image: node:16


pipelines:
  default:
  - step:
      name: Deploy to VM
      deployment: Modulo Planeamento
      script:
      - echo "Deploying to VM"
      - cat deployPlaneamento.sh | ssh pipelineuser@vs1141.dei.isep.ipp.pt
      - echo "Deployment step finished"