image: node:16


pipelines:
  default:
    - parallel:
        - step:
            name: Build and Test
            caches:
              - node
            script:
              - npm install
              - npm test
        - step:
            name: Code linting
            script:
              - npm install eslint
              - npx eslint .
            caches:
              - node
        - step:
            name: Deploy Modulo Planeamento to VM
            deployment: production
            script:
            - echo "Declaring pipeline variables"
            - sudopass=$sudopass
            - echo "export sudopass=$sudopass" >> set_env.sh
            - source set_env.sh
            - echo "Deploying Modulo Planeamento to VM"
            - cat deployPlaneamento.sh | ssh pipelineuser@vsgate-ssh.dei.isep.ipp.pt -p 11141
            - echo "Deployment step finished
