image: node:16


pipelines:
  default:
    - parallel:
        - step:
            name: Build and Test
            caches:
              - node
            script:
              - npm install
              - npm test
#        - step:
#            name: Code linting
#            script:
#              - npm install eslint
#              - npx eslint .
#            caches:
#              - node
        - step:
            name: Deploy Modulo Planeamento to VM
            deployment: test
            script:
            - cat deployPlaneamento.sh | ssh -t pipelineuser@vsgate-ssh.dei.isep.ipp.pt -p 11141
            - echo "Deployed Modulo Planeamento to VM"
