@startuml



participant GestaoDeInformacao <<component>>



?o-> GestaoDeInformacao : editar elevador no edificio
activate GestaoDeInformacao


?<-- GestaoDeInformacao  : saved elevador
deactivate GestaoDeInformacao


@enduml
