@startuml



participant GestaoDeInformacao <<component>>



?o-> GestaoDeInformacao : criar edificio
activate GestaoDeInformacao
GestaoDeInformacao --> GestaoDeInformacao: criar edificio

GestaoDeInformacao ->o] : save edificio
]-> GestaoDeInformacao : saved edificio

?<-- GestaoDeInformacao  : saved edificio
deactivate GestaoDeInformacao


@enduml
