@startuml

package RobDroneGo{
    package Planeamento{

    }

    package GestaoDeInformacao{

    }

    package Visualizacao{

    }
}

Visualizacao ..> Planeamento
Planeamento ..> GestaoDeInformacao

@enduml
