@startuml



participant RobDroneGo <<system>>



?o-> RobDroneGo : criar piso
activate RobDroneGo
RobDroneGo --> RobDroneGo :criar piso

RobDroneGo ->o] : save piso
]-> RobDroneGo : saved piso

?<-- RobDroneGo  : saved piso
deactivate RobDroneGo


@enduml
