@startuml Domain Model

title "Domain Model"
' left to right direction
' top to bottom direction
skinparam Padding 10
skinparam Nodesep 80
skinparam ranksep 100
skinparam groupInheritance 1
' skinparam linetype ortho
skinparam separation 1000
skinparam NoteBackgroundColor #A9A9A9
skinparam PackageStyle rectangle
skinparam package {
    BackgroundColor #D3D3D3
    FontStyle bold
}

' hide circle
' hide methods

package Robot {
    entity Robot <<Agregate root>>{
        -marca
        -modelo
        -numeroDeSerie
        -estado
        -codigo
        -nickname
    }
}

package TipoDeRobot {
    Enum TipoDeRobot {
    }
}

package TipoTarefa{
    enum TipoTarefa{
        -Vigilancia
        -Transporte
    }
}

package Tarefa {
    interface Tarefa <<Agregate root>>{
        - codigo
        - descricao

    }

    entity TarefaVigilancia {
        - nrEmergencia
    }
    entity TarefaTransporte {
        - nomeRemetente
        - nomeDestinatario
        - contatoRemetente
        - contatoDestinatario
        - codigoConfirmacao
    }
}

package Edificio{
    entity Edificio <<Agregate root>>{
        - codigo
        - nome
        - descricao
        - dimensao
    }
}

package Piso{
    entity Piso <<Agregate root>> {
        - descricao
    }

}

package Elevador {
    entity Elevador <<Agregate root>> {
      }
}

package Sala{
    Entity Sala <<Agregate root>> {
        - descricao
    }

    enum CategoriaSala <<enum>>{
            - SalaDeAula
            - Gabinete
            - Laboratorio
            - Auditorio
    }
}

package Passagem{
    entity Passagem <<Agregate root>>{
    }
}

TarefaVigilancia ..|> Tarefa: estende
TarefaTransporte ..|> Tarefa: estende

Sala --> CategoriaSala: tipo

TipoDeRobot --> "*" TipoTarefa: executa

Piso "*" <-- Edificio: tem
Piso "*" <-- Elevador : serve
Piso --> "*" Sala: tem

Elevador --> Edificio: pertence

TarefaTransporte --> Piso: destino
TarefaTransporte --> Piso: origem

TarefaVigilancia --> Piso: destino

Passagem --> "2" Piso: tem

Robot --> TipoDeRobot : é de

Tarefa --> TipoTarefa : é de

Robot ..> "*" Tarefa : executa

@enduml
