@startuml
skinparam layoutDirection top to bottom
skinparam padding 10

component  GestaoDeInformacao <<system>> {

    package "Framework and DriversLayer"{
        component Routing  <<component>>{

        }

        component Persistence  <<component>>{

        }
    }


    package "Interface And AdaptersLayer"{
        component Controller as ctrl <<component>>{

        }

        component Repository as Repo <<component>>{

        }
    }


    package "Application Business Rules" {
        component Application_Service as Service  <<component>>{

        }
    }

    package "Enterprise Business Rules" {
        component Domain_Model(DDD) as Domain <<component>>{

        }
    }

component DTO <<component>>{

}

component DataModel <<component>>{

}

() ModelApi
() APP_Service_API
() DTO_API
() RepoApi
() DataModelApi
() ControllerApi
() PersistenceApi

ControllerApi  )-- Routing
Persistence #-- PersistenceApi
DataModelApi  )-- Persistence

Domain #-- ModelApi
ModelApi  )-- Service
ModelApi  )-- Repo

DTO  #--  DTO_API
DTO_API  )-- ctrl
DTO_API  )-- Service

Service #-- APP_Service_API
APP_Service_API  )-- ctrl

Repo #-- RepoApi
RepoApi  )-- Service

ctrl  #-- ControllerApi

PersistenceApi  )-- Repo

DataModel #-- DataModelApi

}

@enduml
